[target.x86_64-unknown-linux-gnu]
linker = "/home/lgl/projects/qiuhaomem/.cargo/gcc-sysroot.sh"
rustflags = [
    "-C", "link-args=--sysroot=/home/lgl/.local/sysroot",
    "-C", "link-args=-L/home/lgl/.local/sysroot/usr/lib/x86_64-linux-gnu/",
]
